#!/bin/ksh
set -ex


. header.sh

#module load python3
module load ecfs

[[ -s $WRK ]] || $MKDIR $WRK
cd $WRK
WDIR=`hostname`$$
Workdir $WDIR


trap "Trapbody $WDIR ; exit 1" 0


dtg=$DTG
date=$(echo $dtg | cut -c1-8)
yyyy=$(echo $dtg | cut -c1-4)
mm=$(echo $dtg | cut -c5-6)
dd=$(echo $dtg | cut -c7-8)
hh=$(echo $dtg | cut -c9-10)

# directory set up
#home=$HM_LIB/carra_grib_convert/archive #/home/ms/no/fab0/carra_grib/grib/archive
carrabin=$HM_LIB/util/carra_grib2/extract/ #  location of script and grib_filter rule files

HM_DATA_PARENT=/scratch/ms/dk/nhx/hm_home/$CARRA_PARENT_EXP/
ARCHIVE_SCRATCH_PARENT=$HM_DATA_PARENT/archive/
ARCHIVE_ECFS_PARENT='ec:/nhx/harmonie/'$CARRA_PARENT_EXP





cat << EOF > ecfs_1
ec:00/fc${date}*grib_fp
ec:00/fc${date}*grib_sfx
ec:00/[b,s]a${date}*grib
ec:00/fc${date}*grib
ec:03/fc${date}*grib_fp
ec:03/fc${date}*grib_sfx
ec:03/[b,s]a${date}*grib
ec:03/fc${date}*grib
ec:06/fc${date}*grib_fp
ec:06/fc${date}*grib_sfx
ec:06/[b,s]a${date}*grib
ec:06/fc${date}*grib
ec:09/fc${date}*grib_fp
ec:09/fc${date}*grib_sfx
ec:09/[b,s]a${date}*grib
ec:09/fc${date}*grib
EOF
cat << EOF > ecfs_2
ec:12/fc${date}*grib_fp
ec:12/fc${date}*grib_sfx
ec:12/[b,s]a${date}*grib
ec:12/fc${date}*grib
ec:15/fc${date}*grib_fp
ec:15/fc${date}*grib_sfx
ec:15/[b,s]a${date}*grib
ec:15/fc${date}*grib
ec:18/fc${date}*grib_fp
ec:18/fc${date}*grib_sfx
ec:18/[b,s]a${date}*grib
ec:18/fc${date}*grib
ec:21/fc${date}*grib_fp
ec:21/fc${date}*grib_sfx
ec:21/[b,s]a${date}*grib
ec:21/fc${date}*grib
EOF


ecd $ARCHIVE_ECFS_PARENT/$yyyy/$mm/$dd
time ecp -F ecfs_1 "--order=tape" "$WRK/grib_tmp/" &
time ecp -F ecfs_2 "--order=tape" "$WRK/grib_tmp/" &

wait

fetched=$(ls -1 $WRK/grib_tmp/)
if [ "$fetched" -lt 178 ];then
  exit 1
fi

for hh in 00 03 06 09 12 15 18 21; do
  [ -d $ARCHIVE_ROOT/$yyyy/$mm/$dd/$hh/ ] || $MKDIR $ARCHIVE_ROOT/$yyyy/$mm/$dd/$hh/
  for file in $(ls $WRK/grib_tmp/*${date}$hh*);do
    mv -n $file $ARCHIVE_ROOT/$yyyy/$mm/$dd/$hh/
  done
done

trap - 0
exit
