#!/bin/bash

set -ax 

. header.sh

[[ -s $WRK ]] || $MKDIR $WRK
cd $WRK
WDIR=`hostname`$$
Workdir $WDIR
trap "Trapbody $WDIR ; exit 1" 0

dtg=$DTG

iy=$(echo $dtg | cut -c1-4)
im=$(echo $dtg | cut -c5-6)
id=$(echo $dtg | cut -c7-8)
ih=$(echo $dtg | cut -c9-10)

inpdir=$ARCHIVE #/scratch/ms/no/fa0e/hm_home/june_output_stage/archive/2014/03/02/00/ # hirlam input files
carrabin=$HM_LIB/util/carra_grib2/extract # where this script and rules' files for grib_filter are 
out1=$WRK/carra_grib && mkdir -p $out1 # output dir for carra fields selected from hirlam input files
out2=$WRK/carra_grib1 && mkdir -p $out2 # output dir for concatenated files
out3=$WRK/carra_grib2 && mkdir -p $out3 #output dir for concatenated files

files_ok=0 #$?
if [ "$files_ok" -eq 0 ]; then
    $carrabin/Select_convert_grib1.bash $iy $im $id $ih || exit 1
else
    exit -1
fi

cd $WRK
rm -rf $WDIR

trap - 0
exit
