#!/bin/bash

set -ax 

. header.sh


echo $ECCODES_DEFINITION_PATH
export ECCODES_DEFINITION_PATH=/usr/local/apps/eccodes/2.15.0/GNU/63/share/eccodes/definitions
GRIB_DEFINITION_PATH_TMP=$GRIB_DEFINITION_PATH
export GRIB_DEFINITION_PATH=""
module swap gcc/6.3.0
module unload grib_api
module unload eccodes
module load eccodes/2.25.0
module load python3/3.8.8-01

[[ -s $WRK ]] || $MKDIR $WRK
cd $WRK
WDIR=`hostname`$$
Workdir $WDIR
trap "Trapbody $WDIR ; exit 1" 0

dtg=$DTG

iy=$(echo $dtg | cut -c1-4)
im=$(echo $dtg | cut -c5-6)
id=$(echo $dtg | cut -c7-8)
ih=$(echo $dtg | cut -c9-10)

inpdir=$ARCHIVE #/scratch/ms/no/fa0e/hm_home/june_output_stage/archive/2014/03/02/00/ # hirlam input files
carrabin=$HM_LIB/util/carra_grib2/extract # where this script and rules' files for grib_filter are 
out1=$WRK/carra_grib && mkdir -p $out1 # output dir for carra fields selected from hirlam input files
out2=$WRK/carra_grib1 && mkdir -p $out2 # output dir for concatenated files
out3=$WRK/carra_grib2 && mkdir -p $out3 #output dir for concatenated files

NPROC=1
echo "NPROC=" $NRPOC

files_ok=0 #$?
if [ "$files_ok" -eq 0 ]; then

  /usr/bin/time python3 $carrabin/Select.py $iy$im$id$ih --carrabin $carrabin --archive $ARCHIVE --npool $NPROC || exit 1
  mv *grib1* $out1/
  
  /usr/bin/time python3 $carrabin/Convert.py --gribdir "$WRK/carra_grib" --cfg "$carrabin/Converters.yml" --npool $NPROC || exit 1
  
  /usr/bin/time $carrabin/Convert_sicesnow.ksh || exit 1
  /usr/bin/time $carrabin/Convert_rad2alb.ksh || exit 1
  /usr/bin/time $carrabin/Cat_uerra.ksh || exit 1

else
    exit -1
fi

cd $WRK
rm -rf $WDIR

trap - 0
exit
