#!/bin/bash

set -ax 

. header.sh


[[ -s $WRK ]] || $MKDIR $WRK
cd $WRK
WDIR=`hostname`$$
Workdir $WDIR
trap "Trapbody $WDIR ; exit 1" 0

dtg=$DTG

if [ "$CARRA_GRIB2_ARCHIVE" == "yes" ];then

   module unload grib_api
   module unload metview
   module load python3
   module load eccodes/2.16.0
   module load metview/5.7.5
   
   if [[ "$DOMAIN" == "CARRA_NE" ]];then
     origin='no-ar-ce'
   elif [[ "$DOMAIN" == "CARRA_SW" || "$DOMAIN" == "IGB" ]];then
     origin='no-ar-cw'
   else
     origin=""
     echo "Unknown domain $DOMAIN"
     exit 1
   fi
  
   if [ "$MARS_DATABASE" == "mars" ];then
      mdb=""
   else
      mdb="--database $MARS_DATABASE"
   fi
 
   python3 $HM_LIB/util/carra_grib2/tools/batch_plot_fields.py '--dtg' $DTG '--source' mars '--origin' $origin $mdb || exit 1
   
   
   [ -d $ARCHIVE_ROOT/gallery ] || $MKDIR $ARCHIVE_ROOT/gallery
   
   mv *.png $ARCHIVE_ROOT/gallery/ || exit 1

   chmod 444 *.png

else
   echo "Skip gallery"
fi

cd $WRK
rm -r $WDIR

trap - 0
exit
