#!/bin/ksh
set -ex


. header.sh

module load python3

[[ -s $WRK ]] || $MKDIR $WRK
cd $WRK
WDIR=`hostname`$$
Workdir $WDIR


trap "Trapbody $WDIR ; exit 1" 0


dtg=$DTG
date=$(echo $dtg | cut -c1-8)
yyyy=$(echo $dtg | cut -c1-4)
mm=$(echo $dtg | cut -c5-6)
dd=$(echo $dtg | cut -c7-8)
hh=$(echo $dtg | cut -c9-10)

# directory set up
#home=$HM_LIB/carra_grib_convert/archive #/home/ms/no/fab0/carra_grib/grib/archive
carrabin=$HM_LIB/util/carra_grib2/extract/ #  location of script and grib_filter rule files

HM_HOME_PARENT=/home/ms/dk/nhx/hm_home/$CARRA_PARENT_EXP/
HM_DATA_PARENT=/scratch/ms/dk/nhx/hm_home/$CARRA_PARENT_EXP/

PARENT_DTG=$(head -n1 /home/ms/dk/nhx/hm_home/$CARRA_PARENT_EXP/progressPP.log | cut -c7-14)

while [ "$date" -ge "$PARENT_DTG" ];do
  sleep 300
  PARENT_DTG=$(head -n1 /home/ms/dk/nhx/hm_home/$CARRA_PARENT_EXP/progressPP.log | cut -c7-14)
done

trap - 0
exit
